### ISSUE TITLE
'run samples/gcd.fir' command giving some error of treadle !

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [ucb-bar/chisel-gui#10]
Hello , I tried the mentioned command in the subject on sbt prompt  in intelliJ IDE ,but it is giving some error like following:
<code/>
[IJ]sbt:chisel-gui> run samples/gcd.fir
<pre/>[info] Compiling 26 Scala sources to D:\chisel-gui-master\target\scala-2.12\classes ...<pre/>
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.6. Compiling...
[info]   Compilation completed in 18.991s.
[error] D:\chisel-gui-master\src\main\scala\visualizer\AppController.scala:156:60: value topName in class TreadleTester cannot be accessed in treadle.TreadleTester
[error]       val fileNameGuess = new File(saveFilePrefix + tester.topName + saveFileSuffix)
[error]                                                            ^
[error] D:\chisel-gui-master\src\main\scala\visualizer\components\MainWindow.scala:78:57: value topName in class TreadleTester cannot be accessed in treadle.TreadleTester
[error]         val suggestedName = AppController.testerOpt.get.topName + ".save"
[error]                                                         ^
[error] D:\chisel-gui-master\src\main\scala\visualizer\components\MainWindow.scala:105:71: value topName in class TreadleTester cannot be accessed in treadle.TreadleTester
[error]         val saveFile = new File(AppController.saveFilePrefix + tester.topName + AppController.saveFileSuffix)
[error]                                                                       ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 31 s, completed 10-Jan-2020, 5:50:38 PM
[IJ]sbt:chisel-gui> 
</code>

So, How can I resolve this?

**Comment by chick** [comment]
chisel-gui is built using current master of treadle. You need to publishLocal versions of Treadle and Firrtl. If you do that I think the error will go away.

**Comment by chick** [comment]
I'm going to close this, please re-open if this error is still occurring
