### ISSUE TITLE
com.apple.eawt.Application import error

### ISSUE THREAD

**Issue by hadirkhan10** [ucb-bar/chisel-gui#23]
After cloning the repository and going into the chisel-gui folder, typing sbt assembly results in the following error:
![Screenshot from 2020-02-11 01-29-24](https://user-images.githubusercontent.com/41375553/74224573-f7c12d00-4c6d-11ea-9f16-e6e3489a4e7b.png)

**Comment by chick** [comment]
I think PR #24 that has just been merged will fix this problem.
Please let me know
Thanks for the report

**Comment by chick** [comment]
Ack, it does not look like this PR fixed the problem. I'm still looking into it

**Comment by chick** [comment]
This should be fixed now by PR #25 , a better solution will have to be found.
